version: '3'

services:


  harena-manager-database:
    image: mysql:5.7
    ports:
      - "10021:3306"
    volumes:
      - harena-manager-database:/var/lib/mysql
    environment:                                # will be  replaced to .env vars, as in ${DB_PASSWORD}
      - MYSQL_DATABASE=harena-manager
      - MYSQL_USER=jacinto
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_PASSWORD=jacinto
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    networks:
      - harena-manager
      

  harena-manager-database-ui:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 10022:80
    environment:
      - PMA_ARBITRARY=0                         # connection to any server 
      - PMA_HOST=harena-manager-database
      - PMA_PORT=10021  
    depends_on:
      - harena-manager-database
    networks:
      - harena-manager


volumes:
  harena-manager-database:
    driver: "local"


networks:
  harena-manager:
    driver: bridge
