version: '3'

services:

  harena-manager:
    image: datasci4health/harena-manager:development
    ports:
      - "10020:10020"
    environment:
      - ENV_SILENT=true
      - HOST=0.0.0.0
      - PORT=10020
      - NODE_ENV=development
      - APP_NAME=harena-manager
      - APP_URL=http://0.0.0.0:10020
      - CACHE_VIEWS=false
      - APP_KEY=vJX37W4ycI2nkVoBbCM8OW1nsP5LAE8l
      - DB_CONNECTION=mysql
      - DB_HOST=harena-manager-database
      - DB_PORT=3306
      - DB_DATABASE=harena-manager
      - DB_USER=jacinto
      - DB_PASSWORD=jacinto
      - HASH_DRIVER=bcrypt
    # env_file:      
    #   - web-variables.env
    depends_on:
      - harena-manager-database
    restart: always  
    networks:
      - harena-manager
    volumes:
      - ./src/adonisjs:/app

  harena-manager-database:
    image: mysql:5.7
    ports:
      - "10021:3306"
    volumes:
      - harena-manager-database:/var/lib/mysql
    environment:                                # will be  replaced to .env vars, as in ${DB_PASSWORD}
      - MYSQL_DATABASE=harena-manager
      - MYSQL_USER=jacinto
      - MYSQL_PASSWORD=jacinto
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    networks:
      - harena-manager
      

  harena-manager-database-ui:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 10022:80
    environment:
      - PMA_ARBITRARY=0                         # connection to any server 
      - PMA_HOST=harena-manager-database
      - PMA_PORT=3306  
    depends_on:
      - harena-manager-database
    networks:
      - harena-manager


volumes:
  harena-manager-database:
    driver: "local"


networks:
  harena-manager:
    driver: bridge
